name: Feature Branch Publish
on:
  push:
    branches:
      - "feature/*"
      - "main/*"

jobs:
  publish:
    uses: ./.github/workflows/build-test-deploy.yml
    with:
      deploy-target: github
    secrets: inherit